@API_HostAddress = https://localhost:7199
@TodoId = T01


GET {{API_HostAddress}}/api/todo/FindById/{{TodoId}}

###

post {{API_HostAddress}}/api/Todo/AddTodo
Content-Type: application/json

{
  "TodoId": "T01",
  "Title": "Title",
  "Description": "description",
  "ScheduleStartDate": "2021-07-01T00:00:00",
  "ScheduleEndDate": "2021-07-01T00:00:00",
  "TodoItemRequests":[
        {
            "TodoItemId":"TD01",
            "Title":"Item1",
            "ScheduleStartDate":"2021-07-01T00:00:00",
            "ScheduleEndDate":"2021-07-01T00:00:00"
        },
        {
            "TodoItemId":"TD02",
            "Title":"Item2",
            "ScheduleStartDate":"2021-07-01T00:00:00",
            "ScheduleEndDate":"2021-07-01T00:00:00"
        }
    ]
}