@host = https://localhost:7113


POST {{host}}/api/todo/FindById
Content-Type: application/json

{
  "TodoId": "TODO01"
}

###

POST {{host}}/api/todo/FindByUserId
Content-Type: application/json

{
  "UserId": "USER01"
}