@host = https://localhost:7113


POST {{host}}/api/todo/FindById
Content-Type: application/json

{
  "TodoId": "TODO01"
}

###

POST {{host}}/api/todo/FindByUserId
Content-Type: application/json

{
  "UserId": "USER01"
}

###
POST {{host}}/api/todo/StartTodo
Content-Type: application/json

{
  "TodoItemId": "TODOITEM01",
  "StartDate":"2024-08-29"
}
###
POST {{host}}/api/todo/FindByUserId2
Content-Type: application/json

{
  "UserId": "USER01"
}